os: unstable

environment:
  matrix:
    - nodejs_version: 7
    - nodejs_version: 6

cache:
  - "%LOCALAPPDATA%/Yarn"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - yarn

test_script:
  - node --version
  - yarn run lint
  - yarn run test
  - yarn run build
  - yarn run test-e2e
  - yarn run package

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1
