name: Test

on: [push, pull_request]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: yarn install
        run: |
          yarn install --frozen-lockfile --network-timeout 300000

      - name: yarn test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn package
          yarn lint
          yarn tsc
          yarn test
          yarn build-e2e

      # - if: matrix.os == 'ubuntu-latest'
      #   run: |
      #   sudo apt-get install libwoff1 libopus0 libwebp6 libwebpdemux2 libenchant1c2a libgudev-1.0-0 libsecret-1-0 libhyphen0 libgdk-pixbuf2.0-0
      #   sudo apt-get install xvfb
      #   export DISPLAY=:99.0
      #   Xvfb -ac :99 -screen 0 1280x1024x16 > /dev/null 2>&1 &

      # TODO: Testcafe e2e are broken because of:
      # https://github.com/DevExpress/testcafe/issues/4512
      # Tests are currently broken on linux and macos
      # - if: matrix.os == 'windows-latest'
      #   run: |
      #     yarn test-e2e
